logging:
  level:
    root: WARN
    '[com.trilobyte.pelisdb]': DEBUG

server:
  port: 8080
spring:
  application:
    name: tempSensors
    version: '@project.version@'
  messages:
    basename: messages.messages
springfox:
  documentation:
    enabled: true
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'